export const docs= [
    {
        "isBestSeller": false,
        "product_title": "Trust: Creating the Foundation for Entrepreneurship in Developing Countries",
        "product_main_image_url": "https://m.media-amazon.com/images/I/71MvAtTYYdL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/B07B4N8DWG",
        "product_id": "B07B4N8DWG",
        "evaluate_rate": "4.7 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Winning in Emerging Markets: A Road Map for Strategy and Execution",
        "product_main_image_url": "https://m.media-amazon.com/images/I/81kFQutcSeL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/1422166953",
        "product_id": "1422166953",
        "evaluate_rate": "4.6 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Tarun Panchal",
        "product_main_image_url": "https://m.media-amazon.com/images/I/81ykqVCw0fL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B09XX1BPHZ",
        "product_id": "B09XX1BPHZ",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "The Number Monster",
        "product_main_image_url": "https://m.media-amazon.com/images/I/71SyJaP99IL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/B0879HK9T1",
        "product_id": "B0879HK9T1",
        "evaluate_rate": "4.8 out of 5 stars",
        "original_price": "$10.99"
    },
    {
        "isBestSeller": false,
        "product_title": "Pehlu (Yoshi & Tarun)",
        "product_main_image_url": "https://m.media-amazon.com/images/I/81ntGRcLKWL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B07YMXN71K",
        "product_id": "B07YMXN71K",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Tarun Banerjee - Modern Bengali Songs",
        "product_main_image_url": "https://m.media-amazon.com/images/I/51Vn7hNKK9L._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B0052ZOULI",
        "product_id": "B0052ZOULI",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "ERYTLLY Classical Twin Bell Alarm Clock for Bedroom with Stereoscopic Dial, Retro Vintage Analog Alarm Clock, Battery Operated Loud Alarm Clock by Retro Style for Home Office-Black",
        "product_main_image_url": "https://m.media-amazon.com/images/I/71YYh4c-aXL._AC_UY218_.jpg",
        "app_sale_price": "10.99",
        "app_sale_price_currency": "$",
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/B07Z5TPYLT",
        "product_id": "B07Z5TPYLT",
        "evaluate_rate": "4.3 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "How to Retire Early With Low Savings: Retirement Income Strategies",
        "product_main_image_url": "https://m.media-amazon.com/images/I/71fXg+0m6IL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/B09QLG7QBJ",
        "product_id": "B09QLG7QBJ",
        "evaluate_rate": "4.7 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Iddari Lokam Okate",
        "product_main_image_url": "https://m.media-amazon.com/images/I/81uRexC7mEL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B08KWQBL1L",
        "product_id": "B08KWQBL1L",
        "evaluate_rate": "2.7 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Chopped: Volume 3 - Season 41",
        "product_main_image_url": "https://m.media-amazon.com/images/I/61HGSadxLzS._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B097LWZS8N",
        "product_id": "B097LWZS8N",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Tarun",
        "product_main_image_url": "https://m.media-amazon.com/images/I/71hRTVd4RWL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B08VZK1QYS",
        "product_id": "B08VZK1QYS",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Java EE to Jakarta EE 10 Recipes: A Problem-Solution Approach for Enterprise Java",
        "product_main_image_url": "https://m.media-amazon.com/images/I/41qURPsAp5L._AC_UY218_.jpg",
        "app_sale_price": "49.99",
        "app_sale_price_currency": "$",
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/1484280784",
        "product_id": "1484280784",
        "evaluate_rate": null,
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Fight Fire with Fire: Proactive Cybersecurity Strategies for Today's Leaders",
        "product_main_image_url": "https://m.media-amazon.com/images/I/41Z+aVaFh4L._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B09GDSXBPH",
        "product_id": "B09GDSXBPH",
        "evaluate_rate": "4.3 out of 5 stars",
        "original_price": "$29.99"
    },
    {
        "isBestSeller": false,
        "product_title": "Barsaat Ki Ek Raat",
        "product_main_image_url": "https://m.media-amazon.com/images/I/81BBMpUS0BL._AC_UY218_.jpg",
        "app_sale_price": "0.99",
        "app_sale_price_currency": "$",
        "isPrime": false,
        "product_detail_url": "https://www.amazon.com/dp/B09DWLNHWG",
        "product_id": "B09DWLNHWG",
        "evaluate_rate": "3.7 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "The Infertility Journey: Real voices. Real issues. Real insights. (Full Color Edition)",
        "product_main_image_url": "https://m.media-amazon.com/images/I/51HeM6DZWyL._AC_UY218_.jpg",
        "app_sale_price": null,
        "app_sale_price_currency": null,
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/1532726244",
        "product_id": "1532726244",
        "evaluate_rate": "4.7 out of 5 stars",
        "original_price": null
    },
    {
        "isBestSeller": false,
        "product_title": "Bhale Dongalu (Tarun & Ileana)",
        "product_main_image_url": "https://m.media-amazon.com/images/I/01RmK+J4pJL._AC_UY218_.gif",
        "app_sale_price": "12.49",
        "app_sale_price_currency": "$",
        "isPrime": true,
        "product_detail_url": "https://www.amazon.com/dp/B001GPLSRC",
        "product_id": "B001GPLSRC",
        "evaluate_rate": "4.3 out of 5 stars",
        "original_price": null
    }
]